// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukqmahsxbwklbaqdhwhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcW1haHN4YndrbGJhcWRod2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDMyMzgsImV4cCI6MjA2NzY3OTIzOH0.bHb4CSbBr6U9ZkFOzkvwqZEfQWlmUqMbYUoz26ZyB30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});